### ISSUE TITLE
back up time

### ISSUE THREAD

**Issue by yogurtnaturalny** [garithd/zimbra-permailbox-backup#6]
Hi

I would like to suggest to set up in config file for how long you would like to keep backups. ( ex 30 days/ day backups or only 2 days or 7 days and  2 weeks.

**Comment by yogurtnaturalny** [comment]
Ok, I will create my own version. Thank You for good base to work with backup zimbra

**Comment by garithd** [comment]
Hey,

Please fork and make a pull request if you'd like to make some cool
changes.  Would be great to have a contributor.

I've been so busy with other projects so been pretty distracted.

Cheers mate,
